name: Build App
on: push
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show installed Xcode versions
      run: ls /Applications | grep 'Xcode'

    - name: Show the version of Xcode to build App
      run: xcodebuild -version

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'ios'
        install-deps: 'true'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        set-env: 'true'

    - name: Show Qt path
      run: echo $QT_ROOT_DIR
      
    - name: Xcode build
      run: set -o pipefail && 
        xcodebuild
          -sdk iphoneos
          -configuration Release
          -project 'Chiaki iOS.xcodeproj'
          -scheme chiaki
          archive
          -archivePath ./
          CODE_SIGNING_ALLOWED=NO
